# How to activate GPU in Google Colab

In [352]:
import tensorflow as tf


In [353]:
cpu_length = tf.config.list_physical_devices('CPU')
gpu_length = tf.config.list_physical_devices("GPU")

In [354]:
print(len(cpu_length))
print(len(gpu_length))

1
0


In [355]:
tf.test.gpu_device_name()

''

# TensorFlow Basic

In [356]:
print("Tensorflow Version:", tf.__version__)

Tensorflow Version: 2.17.1


### Introduction To Tensors

In [357]:
# create tensor with tf.constant
scalar = tf.constant(1)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [358]:
# check the number of dimension of the tensor
scalar.ndim

0

In [359]:
# create vector
vector = tf.constant([20,23,30],dtype=tf.float16)
vector

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([20., 23., 30.], dtype=float16)>

In [360]:
vector.ndim

1

In [361]:
# matrix
matrix = tf.constant(range(0,10),shape=(2,5))
matrix

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int32)>

In [362]:
matrix.ndim

2

In [363]:
# tensor

tensor = tf.constant([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]
])
tensor
# size 3-2-3

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [364]:
tensor.ndim


3

In [365]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

### **CREATING TENSOR WITH "tf.variable"**

In [366]:
changeable_tensor = tf.Variable(3)
not_changeable_tensor = tf.constant(2)

In [367]:
changeable_tensor

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [368]:
changeable_tensor.assign(1233)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=1233>

In [369]:
changeable_tensor.assign_add(2000)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=3233>

In [370]:
print(changeable_tensor.assign_sub(1000))

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=2233>


In [371]:
vector_tensor = tf.Variable([
    [10,20,30],
    [40,50,60]
])

In [372]:
vector_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>

In [373]:
vector_tensor_var = tf.Variable([
    [10,20,30],
    [40,50,60]
])
vector_tensor_con = tf.constant([
    [10,20,30],
    [40,50,60]
])

In [374]:
vector_tensor_con.ndim

2

In [375]:
vector_tensor_var.assign_add([
    [1,2,3],
    [4,3,2]
])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[11, 22, 33],
       [44, 53, 62]], dtype=int32)>

In [376]:
vector_tensor_var.get_shape()

TensorShape([2, 3])

In [377]:
vector_tensor_var[0].assign([99,99,99])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[99, 99, 99],
       [44, 53, 62]], dtype=int32)>

In [378]:
vector_tensor_var + vector_tensor_var

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[198, 198, 198],
       [ 88, 106, 124]], dtype=int32)>

In [379]:
# return value

tensor_one = tf.Variable(3)
tensor_one.assign(31,read_value=False)

In [380]:
tensor_one

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=31>

### Create Random Tensors

In [381]:
random_sample = tf.random.uniform([2,3],minval=3,seed=10)
random_sample

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.6216371, 2.206255 , 1.5831423],
       [2.879212 , 1.6750119, 1.1894977]], dtype=float32)>

In [382]:
tf.random.uniform([2,3],minval=3,seed=10)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.132844 , 2.235246 , 1.4258182],
       [1.4427366, 1.103714 , 1.3029346]], dtype=float32)>

In [383]:
# generate random sample from normal distribution, showing that the data near to mean are most frequently occurring than the data far from the mean

In [384]:
# sample one
normal_sample_one = tf.random.Generator.from_seed(42)
normal_sample_one= normal_sample_one.normal((3,2))

# sample two
normal_sample_two = tf.random.Generator.from_seed(42)
normal_sample_two= normal_sample_two.normal((3,2))


In [385]:
normal_sample_one

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [386]:
normal_sample_two

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [387]:
normal_sample_one == normal_sample_two

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

# Shuffiling the order of the tensors

In [388]:
sample = tf.constant(
   normal_sample_one
)

In [389]:
sample

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [390]:
sample.shape

TensorShape([3, 2])

In [391]:
# shuffiling the tensor 2 dimension

tf.random.shuffle(sample)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702]], dtype=float32)>

In [392]:
# shuffiling one dimension tensor are aslo know as vector
one_dim = tf.constant([1,2,3,4])
tf.random.shuffle(one_dim)

# scalar - 0 dim tensors
# vector - 1 dim tensors
# matrix - 2 dim tensors
# tensors - n dim tensors


# what are tensors ?
# tensors are the numberical representation of the data in array is known as tensors.

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 1, 4, 2], dtype=int32)>

In [393]:
tf.random.set_seed(42)
tf.random.shuffle(one_dim,seed=42)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 1, 4], dtype=int32)>

In [394]:
tf.random.shuffle(one_dim,seed=42)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 3, 4, 2], dtype=int32)>

## Create Tensor Using Numpy

In [395]:
import numpy as np

array = np.arange(1,10)

In [396]:
tf.constant(array,shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [397]:
ones = np.ones((2,3)).reshape(6,1)
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [398]:
tf.constant(ones)

<tf.Tensor: shape=(6, 1), dtype=float64, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])>

In [399]:
# using tensorflow "tf.one"

In [400]:
tf.ones((2,4),dtype=tf.float64)

<tf.Tensor: shape=(2, 4), dtype=float64, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])>

In [401]:
tf.eye(2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [402]:
batch_identity = tf.eye(2, batch_shape=[3])

In [403]:
batch_identity

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]]], dtype=float32)>

In [404]:
tf.zeros(shape=(4,10),dtype=tf.float64)

<tf.Tensor: shape=(4, 10), dtype=float64, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])>

In [405]:
vector_X = np.arange(1,31) # Capitail one-dim tensor are also known as vector
vector_X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [406]:
tf.constant(vector_X,shape=(3,10))

<tf.Tensor: shape=(3, 10), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])>

In [407]:
# 3-dimension tensors

tf.constant(vector_X, shape=(2,3,5) )

<tf.Tensor: shape=(2, 3, 5), dtype=int64, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])>

In [408]:
# create a tensor and fill with scaler value
tf.fill((3,4),4) + 15

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19]], dtype=int32)>

### Getting Informaition from the tensors
When deal with tensors we probably want to be aware of the following terms
* Shape
* Rank/Dimension
* Axis
* Size


In [409]:
scores = np.arange(20,35).reshape(3,5)
scores = tf.constant(scores)

In [410]:
scores

<tf.Tensor: shape=(3, 5), dtype=int64, numpy=
array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])>

In [411]:
scores.ndim

2

In [412]:
scores.shape

TensorShape([3, 5])

In [413]:
four_dim_tensor = tf.ones((2,3,3,5))
four_dim_tensor

<tf.Tensor: shape=(2, 3, 3, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [414]:
print("shape of the tensor",four_dim_tensor.shape)
print("dimention of tensor",four_dim_tensor.ndim)
print("items in tensor",tf.size(four_dim_tensor).numpy())

shape of the tensor (2, 3, 3, 5)
dimention of tensor 4
items in tensor 90


In [415]:
four_dim_tensor[0].ndim

3

In [416]:
four_dim_tensor[0]

<tf.Tensor: shape=(3, 3, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [417]:
# Create (2 dimension) tensor
rank_2_tensor= tf.constant([
    [77,8],
    [12,43]
])

In [418]:
rank_2_tensor.shape, rank_2_tensor.ndim


(TensorShape([2, 2]), 2)

In [419]:
# how to get the last item of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 8, 43], dtype=int32)>

In [420]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[77,  8],
       [12, 43]], dtype=int32)>

## How to add dimension to tensor

In [421]:
foo = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
foo

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [422]:
# add dimension outer most
foo[tf.newaxis,:,:]

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [423]:
foo[tf.newaxis,...]

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [424]:
# add middle
foo[:,tf.newaxis,:]

<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]], dtype=int32)>

In [425]:
# now add axis most inner layer
foo[...,tf.newaxis]



<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]], dtype=int32)>

In [426]:
tf.constant(
[
  [ [1],[2],[3] ],
  [ [4],[5],[6] ],
  [ [7],[8],[9] ]
])

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]], dtype=int32)>

In [427]:
# using aternative method "tf.expand_dims"
foo


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [428]:
# we can add dimension using tf.expand_dims method
add_new_axis_tensor = tf.expand_dims(foo,0)
print(add_new_axis_tensor)
print(add_new_axis_tensor.shape)

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(1, 3, 3), dtype=int32)
(1, 3, 3)


In [429]:
tf.expand_dims(foo,1)


<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]], dtype=int32)>

In [430]:
tf.expand_dims(foo,2)

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]], dtype=int32)>

In [431]:
tf.expand_dims(foo,-1) ==  tf.expand_dims(foo,2)

<tf.Tensor: shape=(3, 3, 1), dtype=bool, numpy=
array([[[ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True]]])>

In [432]:
 foo

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [433]:
foo.shape

TensorShape([3, 3])

In [434]:
foo[...,tf.newaxis]



<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]], dtype=int32)>

In [435]:
# shape to list
foo.shape.as_list()

[3, 3]

In [436]:
foo

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

## Manipulation tensor with Basic Operations
**Basic Operations**
+ plus "+"
+ subtraction "-"
+ multiplication "*"
+ division "/"



In [437]:
tensor_one = np.arange(10,20)
tensor_two = np.arange(0,10)
print(tensor_one)
print(tensor_two)

[10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]


In [438]:
tensor_one = tf.constant(tensor_one)
tensor_two =  tf.constant(tensor_two)
print(tensor_one)
print(tensor_two)

tf.Tensor([10 11 12 13 14 15 16 17 18 19], shape=(10,), dtype=int64)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int64)


In [439]:
tensor_one + tensor_two

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])>

In [440]:
tensor_one - tensor_two

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])>

In [441]:
tensor_one / tensor_two

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([        inf, 11.        ,  6.        ,  4.33333333,  3.5       ,
        3.        ,  2.66666667,  2.42857143,  2.25      ,  2.11111111])>

In [442]:
tensor_one+ 10

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])>

## BroadCasting In Tensorflow

In [443]:
tensor = tf.constant([
    [7,10],
    [5,6]
])

In [444]:
tensor.shape

TensorShape([2, 2])

In [445]:
tensor +  10
# [
#     [7,10],
#     [5,6]
# ]

# [
#     [10,10],
#     [10,10]
# ]



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 20],
       [15, 16]], dtype=int32)>

In [446]:
# tensorflow build in function for basic operation like +,-,etc
tensor_one

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])>

In [447]:
tensor_one

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])>

In [448]:
tf.reshape(tensor_one,(2,5)) # reshape the tensor

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])>

In [449]:
print(tf.rank(tensor_one).numpy())
print(tensor_one.ndim)

1
1


In [450]:
tf.add(tensor_one,1)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])>

In [451]:
tf.subtract(tensor_one,1)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])>

In [452]:
foo

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [453]:
foo * [[2,1,1],[3,1,1],[1,1,1]]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  2,  3],
       [12,  5,  6],
       [ 7,  8,  9]], dtype=int32)>

In [454]:
foo

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [455]:

foo @ foo

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

In [456]:
foo * foo

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)>

In [457]:
# we can use the tensorflow build in function tf.linalg.mutmul

tf.matmul(foo,foo)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

In [458]:
tensor_one = tf.constant(
    [
        [1,2,5],
        [7,2,1],
        [3,3,3]
    ]
)
tensor_two = tf.constant(
    [
        [3,5],
        [6,7],
        [1,8]
    ]
)

In [459]:
tensor_one @ tensor_two

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [460]:
# build in function to multiplicaton of the tensor
tf.matmul(tensor_one,tensor_one)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[30, 21, 22],
       [24, 21, 40],
       [33, 21, 27]], dtype=int32)>

In [461]:
tensor_one = tf.Variable([
    [1,2,3],
    [3,4,5]
])

In [462]:
tensor_one[0].assign([1,1,1])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [3, 4, 5]], dtype=int32)>

In [463]:
tensor_one.assign_add([[5,5,5],[5,5,5],])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 6,  6,  6],
       [ 8,  9, 10]], dtype=int32)>

In [464]:
# (3,2) tensor
tensor_one  = tf.constant(np.arange(1,7),shape=(3,2))
tensor_two = tf.constant(np.arange(7,13),shape=(3,2))
tensor_one, tensor_two

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [465]:
# matrix multiplication of same dimentions it will show error

# tensor_one @ tensor_two

In [466]:
# tf.matmul(tensor_one,tensor_two)

In [467]:
tf.matmul(tf.reshape(tensor_one,[2,3]),tensor_two)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 58,  64],
       [139, 154]])>

In [468]:
tensor_one.shape,tensor_two.shape,tf.reshape(tensor_one,[2,3]).shape

(TensorShape([3, 2]), TensorShape([3, 2]), TensorShape([2, 3]))

In [469]:
# transpose in tensorflow

tensor_one # (3 rows ,2 colums)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [470]:
tf.transpose(tensor_one)

# [[1,3,5],[2,4,6]]

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [471]:
tensor_one

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [472]:
tf.matmul(tf.transpose(tensor_one),tensor_one)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[35, 44],
       [44, 56]])>

In [473]:
tensor_one

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [474]:
print("normal tensor:")
print(tensor_one,"\n")
print('transpose tensor:','\n',tf.transpose(tensor_one),"\n")
print("reshape tensor:", tf.reshape(tensor_one,shape=(2,3)))



normal tensor:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int64) 

transpose tensor: 
 tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int64) 

reshape tensor: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [475]:
tf.tensordot(tf.transpose(tensor_one),tensor_one,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[35, 44],
       [44, 56]])>

## Change the data type of the tensor

In [476]:
tensor_one

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [477]:
# caste a tensor to new data type
print(tensor_one.dtype)

tf.cast(tensor_one,dtype=tf.float16)

<dtype: 'int64'>


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [478]:
tf.__version__

'2.17.1'

In [479]:
tf.constant([1.2])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>

In [480]:
tf.constant([1])

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

Aggregation In TensorFlow

In [481]:
tensor = tf.Variable([
    -1,-2
])
print(tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([-1, -2], dtype=int32)>


In [482]:
# what is aggregation?
# Aggregtion is the collection of the units in to a whole. Multiple value to some values

tensor = tf.abs(tensor)

In [483]:
# sum of the tensor
tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [484]:
tf.reduce_sum(tensor).numpy()

3

In [485]:
#
tensor_2dim = tf.constant([
  [1,2,3],
  [4,5,6]
])

In [486]:
tf.reduce_sum(tensor_2dim)
# sum all the element in the tensor

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [487]:
tf.reduce_sum(tensor_2dim,axis=0)
# sum the value by columns
# output = [5,7,9]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [488]:
tf.reduce_sum(tensor_2dim,axis=1)
# sum all the value by the row
# output = [6,15]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 6, 15], dtype=int32)>

In [489]:
tf.reduce_sum(tensor_2dim,keepdims=True,axis=1)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 6],
       [15]], dtype=int32)>

In [490]:
tf.reduce_sum(tensor_2dim,keepdims=True,axis=0)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[5, 7, 9]], dtype=int32)>

In [491]:
# mean of the tensor

print(tf.reduce_mean(tensor_2dim.numpy().astype(np.float16)))
# x = tf.constant([[1,2,3], [4,5,6]])
# tf.reduce_mean(x)
# print(tensor_2dim)
# print(x)

# another method

print(tf.reduce_mean(tf.cast(tensor_2dim,dtype=tf.float16)))



tf.Tensor(3.5, shape=(), dtype=float16)
tf.Tensor(3.5, shape=(), dtype=float16)


In [492]:
# min and max value of the tensor

print(tensor_2dim.numpy().min())
# another method
min_value = tf.reduce_min(tensor_2dim).numpy()
max_value = tf.reduce_max(tensor_2dim).numpy()
print("min value of the tensor is:",min_value)
print("max value of the tensor is:",max_value)

1
min value of the tensor is: 1
max value of the tensor is: 6


In [493]:
tensor_2dim.numpy().max()

6

In [494]:
# variance and standard deviation of the tensor
x = tf.constant([[1., 2.], [3., 4.]])
variance = (tf.reduce_mean(x).numpy() -1) **2 + (tf.reduce_mean(x).numpy()-2)**2+(tf.reduce_mean(x).numpy() -3 )**2+(tf.reduce_mean(x).numpy()-4 )**2
variance/4



1.25

In [495]:
# using pre build function of tensorflow
tf.math.reduce_variance(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.25>

In [496]:
tf.math.reduce_std(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.118034>

In [497]:
 import tensorflow_probability as tfp
 tfp.stats.variance(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

## Find the position of Max and Min of Tensor

In [498]:
A = tf.constant([2, 20, 30, 3, 6])

In [499]:
tf.math.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [500]:
tf.math.argmin(A)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [525]:
tf.random.set_seed(5);
data = tf.random.normal([1,1,1,1,50])

In [529]:
data.shape,tf.size(data), data.ndim

(TensorShape([1, 1, 1, 1, 50]),
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 5)

In [530]:
# Remove the dimension of size one from the tensor

tf.squeeze(data)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([-0.18030666, -0.95028627, -0.03964049, -0.7425406 ,  1.3231523 ,
       -0.61854804,  0.8540664 , -0.08899953,  2.4488697 ,  0.762508  ,
        1.2659615 ,  0.9801489 ,  1.5293121 , -0.57500345,  0.8987044 ,
       -1.250801  , -0.8604956 ,  1.260746  , -0.6830498 ,  0.02615766,
        0.22328745,  0.95914024, -0.37048063,  0.03484769,  0.13794525,
        0.7596925 ,  0.4640491 , -1.3800851 , -0.47065532,  1.1383884 ,
       -0.91330576,  0.74427116, -0.67893195, -0.83569556, -0.49823263,
       -0.9336107 , -0.00845589, -0.04050136,  2.0187025 , -1.4186655 ,
       -0.90990627,  1.1692344 , -0.1118804 ,  0.32484442, -1.4201527 ,
       -1.5693021 , -0.56799746, -0.15874937,  0.18945342,  0.9961622 ],
      dtype=float32)>

In [538]:
# one-hot encoding of tensor

indices = [1,2,3,4,4]
depth = 3
tf.one_hot(indices, depth)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [552]:
# change the default value of one-hot encoding

tf.one_hot(indices,5,off_value=3,on_value=1)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[3, 1, 3, 3, 3],
       [3, 3, 1, 3, 3],
       [3, 3, 3, 1, 3],
       [3, 3, 3, 3, 1],
       [3, 3, 3, 3, 1]], dtype=int32)>

In [565]:
# math build in function
# squaring, loging, square root
print("Square of :",tf.square([10]),"\n")

x = tf.constant([0, 0.5, 1, 5])
print("log of 10 is:",tf.math.log(x),"\n")

print(tf.math.sqrt(x))


Square of : tf.Tensor([100], shape=(1,), dtype=int32) 

log of 10 is: tf.Tensor([      -inf -0.6931472  0.         1.609438 ], shape=(4,), dtype=float32) 

tf.Tensor([0.         0.70710677 1.         2.236068  ], shape=(4,), dtype=float32)


## Tensor and numpy

In [567]:
a = tf.constant([1,2,4])
a.dtype

tf.int32

In [568]:
b = np.array([1,2,4])
b.dtype

dtype('int64')

In [570]:
c = tf.constant([1.,2.,3.])
c.dtype

tf.float32

In [571]:
d = np.array([1.,2.,3.])
d.dtype

dtype('float64')

In [572]:
# from the above 4 statement we come to know that the default datatype of tensorflow is int32 and float32 and for numpy int64 and float64

🔑 the main difference between the tensorflow tensor and numpy is that tensorflow tensor run on gpu or tup and numpy run on cpu

In [2]:
!nvidia-smi

Fri Jan 17 20:41:52 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--